"""
modules/mailer.py
Sends the daily Pulse digest via Gmail SMTP (or any SMTP server).
Renders the email_template.html Jinja2 template.
"""

import os
import smtplib
import traceback
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader


def send_daily_digest(payload: dict) -> dict:
    """
    Renders email_template.html with `payload` and sends it.
    `payload` should contain the same keys as the dashboard context.

    Returns {"ok": True/False, "msg": str}.
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")
    email_to  = os.getenv("EMAIL_TO", smtp_user)

    if not smtp_user or smtp_user == "your_email@gmail.com":
        return {"ok": False, "msg": "SMTP credentials not configured in .env"}

    try:
        # Render HTML body
        template_dir = Path(__file__).parent.parent / "templates"
        env = Environment(loader=FileSystemLoader(str(template_dir)),
                          autoescape=True)
        template = env.get_template("email_template.html")
        html_body = template.render(
            **payload,
            sent_at=datetime.now().strftime("%A, %B %d %Y · %H:%M"),
        )

        # Build message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🌅 Pulse Daily — {datetime.now().strftime('%a %b %d')}"
        msg["From"]    = smtp_user
        msg["To"]      = email_to
        msg.attach(MIMEText(html_body, "html"))

        # Send
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [email_to], msg.as_string())

        return {"ok": True,
                "msg": f"Digest sent to {email_to} at {datetime.now().strftime('%H:%M')}"}

    except smtplib.SMTPAuthenticationError:
        return {"ok": False,
                "msg": "SMTP authentication failed. Check SMTP_USER / SMTP_PASS in .env."}
    except Exception:
        return {"ok": False, "msg": traceback.format_exc()}


def save_text_summary(payload: dict, path: str = "reports/summary.txt") -> None:
    """
    Write a plain-text daily summary to disk (always succeeds).
    Useful as a local backup even when email is not configured.
    """
    lines = [
        f"PULSE DAILY SUMMARY — {datetime.now().strftime('%A %B %d %Y, %H:%M')}",
        "=" * 60,
    ]

    # Weather
    if w := payload.get("weather", {}).get("current"):
        lines.append(
            f"\n🌤  WEATHER ({w['city']})\n"
            f"    {w['icon']} {w['temp']}{w['unit']} — {w['description']}\n"
            f"    Humidity: {w['humidity']}%  Wind: {w['wind_kph']} km/h"
        )

    # Quote
    if q := payload.get("quote"):
        lines.append(f"\n💬  QUOTE\n    \"{q['text']}\"\n    — {q['author']}")

    # GitHub
    if gh := payload.get("github"):
        if not gh.get("error"):
            lines.append(
                f"\n🐙  GITHUB ({gh['username']})\n"
                f"    Repos: {gh['public_repos']}  Followers: {gh['followers']}\n"
                f"    Streak: {gh['streak_days']} day(s)"
            )
            for c in gh.get("recent_commits", [])[:3]:
                lines.append(f"    • [{c['repo']}] {c['message']} ({c['time']})")

    # Study
    if st := payload.get("study"):
        lines.append(
            f"\n📚  STUDY (7-day)\n"
            f"    Total: {st['total_hours']}h across {st['session_count']} sessions\n"
            f"    Today: {st['today_min']} min"
        )

    # System
    if sys := payload.get("system"):
        if not sys.get("error"):
            lines.append(
                f"\n💻  SYSTEM\n"
                f"    CPU: {sys['cpu']['percent']}%  "
                f"RAM: {sys['ram']['percent']}%  "
                f"Disk: {sys['disk']['percent']}%\n"
                f"    Uptime: {sys['uptime']}"
            )

    # News headlines
    if news := payload.get("news"):
        lines.append("\n📰  TOP HEADLINES")
        for topic, articles in news.items():
            lines.append(f"\n  [{topic.upper()}]")
            for a in articles[:2]:
                lines.append(f"    • {a['title']} ({a['source']})")

    lines.append("\n" + "=" * 60)
    lines.append("Generated by Pulse — your personal morning dashboard.")

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines))